### PR TITLE
Fix issue with toJson

### LINKED ISSUE #81: settings endpoint will only return last saved value
I am not sure if this was a design choice or bug but when saving with a PUT to `/settings` and then calling the GET on `/settings` only the last value is returned. 

I was playing with these 2 functions and I do not know enough about c++ to fix but wanted to bring this up.
https://github.com/nrwiersma/ConfigManager/blob/master/src/ConfigManager.h#L82-L88
and 
https://github.com/nrwiersma/ConfigManager/blob/master/src/ConfigManager.cpp#L177-L194

I confirmed with the save_config_demo example that it does this as it will only show he meta.version (I removed to test the form code)
I also confirmed it will save the values to EPROMM so it's working in that part.

EDIT: I am going to play with a solution using 
https://arduinojson.org/v6/how-to/merge-json-objects/

Thanks

### PR DESCRIPTION
**Pull request by nrwiersma**
This is a potential fix for a toJson issue. 

Fixes #81.

### CODE REVIEW

File: src/ConfigManager.h [hunk 1]
```diff
@@ -81,10 +81,7 @@ class ConfigParameter : public BaseParameter {
 
   void toJson(JsonObject* json) {
     // json->set(name, *ptr);
-    DynamicJsonDocument doc(1024);
-    JsonObject obj = doc.to<JsonObject>();
-    obj.operator[](name) = *ptr;
-    json->set(obj);
+    json->getOrAddMember(name).set(*ptr);
```
Comment (cgmckeever) [inline src/ConfigManager.h:84]: LGTM .. not sure though ;)

**Comment by drifterz28** [comment]
I am testing on an esp8266 wemos d1 mini and it works 👍

**Comment by nrwiersma** [comment]
Thanks, will version it in the morning.
