### PR TITLE
Dont check EEPROM length on ESP32

### LINKED ISSUE #75: Saving credentials does not work
Thanks for this great library. I am trying to get it running on an ESP32 via PlatformIO.
In the log I can see this output during boot and when I try to save my Wifi credentials.

> Starting Access Point
AP Name: SolarPowerReader
AP IP address: 192.168.1.1
Webserver enabled on port: 80
dhcps: send_offer>>udp_sendto result 0
[E][WebServer.cpp:617] _handleRequest(): request handler not found
Unknown URL: www.msftconnecttest.com
_--> at this point I hit save in the browser to store the credentials <--_
WiFi Settings cannot be stored before ConfigManager::begin()
ets Jun  8 2016 00:22:57

The code for testing:

```cpp
#include <Arduino.h>
#include "ConfigManager.h"

struct Config
{
  char name[20];
  bool enabled;
  int8_t hour;
  char password[20];
} config;
struct Metadata
{
  int8_t version;
} meta;

ConfigManager configManager;
const long interval = 30000;
// the logic should be triggered on the first run and not after the interval
unsigned long previousMillis = millis() - interval;

void setup()
{
  DEBUG_MODE = true; // will enable debugging and log to serial monitor

  Serial.begin(115200);
  Serial.println("\n\nbooting...\n\n");

  meta.version = 3;

  // Setup config manager
  configManager.setAPName("SolarPowerReader");
  configManager.setAPFilename("/index.html");
  configManager.addParameter("name", config.name, 20);
  configManager.addParameter("password", config.password, 20, set);
  configManager.addParameter("version", &meta.version, get);

  configManager.begin(config);
  // configManager.clearWifiSettings(false);
  //configManager.save();
}

void loop()
{
  configManager.loop();

  unsigned long currentMillis = millis();
  // query Modbus if interval is reached and Wifi is connected
  if (currentMillis - previousMillis >= interval && configManager.getMode() != 0)
  {
    previousMillis = currentMillis;

    Serial.println("do something");
  }
}
```

I think it might have to do with the EPROM. Trying to call clearWifiSettings or save did result in the same behaviour.

### PR DESCRIPTION
**Pull request by nrwiersma**
Fixes #75

### CODE REVIEW

File: src/ConfigManager.cpp [hunk 1]
```diff
@@ -376,10 +376,13 @@ void ConfigManager::storeWifiSettings(String ssid, String password, bool resetMa
     char ssidChar[SSID_LENGTH];
     char passwordChar[PASSWORD_LENGTH];
 
+    // We cannot check the EEPROM length on ESP32
+#if defined(ARDUINO_ARCH_ESP8266)
     if (EEPROM.length() == 0) {
         DebugPrintln(F("WiFi Settings cannot be stored before ConfigManager::begin()"));
         return;
     }
+#endif
```
Comment (cgmckeever) [inline src/ConfigManager.cpp]: If it works, LGTM
